font-family = "CaskaydiaMono Nerd Font Mono"

background = #1b1112
foreground = #ffffff

cursor-color = #ffffff
cursor-text  = #1b1112

selection-background = #372223
selection-foreground = #ffffff

palette = 0=#1A0E0E
palette = 1=#b33a3a
palette = 2=#C05A5A
palette = 3=#D66B6B
palette = 4=#1e90ff
palette = 5=#bf7b75
palette = 6=#d97a7a
palette = 7=#F2E8E8
palette = 8=#2B1818
palette = 9=#ff3a3a
palette = 10=#D97171
palette = 11=#E87F7F
palette = 12=#60b8ff
palette = 13=#d99189
palette = 14=#e89494
palette = 15=#FFF1F1
