animations {
    enabled = yes

    bezier = spring, 0.55, 1.2, 0.45, 1.0
    bezier = smooth, 0.3, 0, 0.25, 1.0
    bezier = quick,  0.2, 0, 0.1,  1.0

    animation = windows,          1, 1.5, spring
    animation = windowsIn,        1, 1.2, quick
    animation = windowsOut,       1, 1.0, quick
    animation = windowsMove,      1, 1.6, spring
    animation = fade,             1, 1.3, smooth
    animation = fadeIn,           1, 1.1, smooth
    animation = fadeOut,          1, 0.9, quick
    animation = fadeDim,          1, 1.1, smooth
    animation = fadeSwitch,       1, 1.2, quick
    animation = layers,           1, 1.5, spring
    animation = layersIn,         1, 1.2, quick
    animation = layersOut,        1, 1.1, quick
    animation = workspaces,       1, 1.5, spring
    animation = specialWorkspace, 1, 1.3, smooth
    animation = border,           1, 2.0, spring
    animation = borderangle,      1, 2.2, smooth
}

general {
    col.active_border   = rgb(bf7b75)
    col.inactive_border = rgba(642425ff)
    border_size = 2
    gaps_in  = 2
    gaps_out = 4
}

decoration {
    rounding = 16

    blur {
        passes = 3
    }

    shadow {
        enabled        = yes
        range          = 26
        render_power   = 5
        color          = rgba(ff3a3a66)
        color_inactive = rgba(00000044)
    }
}
