$accent_red   = rgba(ff3a3aff)
$foreground   = rgba(ffffffff)
$shadow_color = rgba(0,0,0,0.55)

general {
    hide_cursor = true
}

input-field {
    size = 1,1
    outline_thickness = 0
    outer_color = rgba(0,0,0,0)
    inner_color = rgba(0,0,0,0)
    font_color  = rgba(0,0,0,0)
    hide_input  = true
    dots_size     = 0.6
    dots_spacing  = 0.4
    dots_center   = true
    dots_rounding = 1
    check_color = $accent_red
    fail_color  = rgba(ff3333ff)
    fail_text   = ""
    fade_on_empty  = true
    fade_timeout   = 1000
    position = 0,0
    halign = center
    valign = center

    glow           = true
    glow_color     = $accent_red
    glow_intensity = 0.3
    glow_speed     = 2
}

decoration {
    rounding     = 999
    blur_size    = 8
    blur_passes  = 2
    shadow_color = $shadow_color
}
