font_family          CaskaydiaMono Nerd Font Mono

foreground           #ffffff
background           #1b1112
selection_foreground #1b1112
selection_background #372223

cursor           #ffffff
cursor_text_color #1b1112

url_color #d4c9b8

active_tab_foreground   #ffffff
active_tab_background   #1b1112
inactive_tab_foreground #d4c9b8
inactive_tab_background #2B2826
tab_bar_background      #1b1112

color0  #1A0E0E
color8  #4b515b
color1  #b33a3a
color9  #ff3a3a
color2  #d13a3a
color10 #d13a3a
color3  #9e3a3a
color11 #9e3a3a
color4  #ad3a3a
color12 #ad3a3a
color5  #c3c8d0
color13 #c3c8d0
color6  #8f949c
color14 #8f949c
color7  #b9bec6
color15 #eceff2
