foreground           #ffffff
background           #1b1112
selection_foreground #1b1112
selection_background #372223

cursor           #ffffff
cursor_text_color #1b1112

url_color #d4c9b8

active_tab_foreground   #ffffff
active_tab_background   #1b1112
inactive_tab_foreground #d4c9b8
inactive_tab_background #2B2826
tab_bar_background      #1b1112

color0  #1A0E0E
color8  #2B1818
color1  #b33a3a
color9  #ff3a3a
color2  #C05A5A
color10 #D97171
color3  #D66B6B
color11 #E87F7F
color4  #1e90ff
color12 #60b8ff
color5  #bf7b75
color13 #d99189
color6  #d97a7a
color14 #e89494
color7  #F2E8E8
color15 #FFF1F1
